# .github/workflows/frontend.yml

name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 18 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm ci

      - name: 프론트엔드 빌드
        run: npm run build

      - name: dist 폴더 압축
        run: zip -r dist.zip dist

      - name: SSH 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.FRONTEND_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.FRONTEND_IP }} >> ~/.ssh/known_hosts

      - name: dist.zip 파일 서버로 전송
        run: scp dist.zip ${{ secrets.FRONTEND_USER }}@${{ secrets.FRONTEND_IP }}:~/dist.zip

      - name: GCP 서버에서 배포 수행
        run: |
          ssh ${{ secrets.FRONTEND_USER }}@${{ secrets.FRONTEND_IP }} << 'EOF'
            rm -rf ~/frontend/dist
            unzip -o ~/dist.zip -d ~/frontend
            rm ~/dist.zip
            echo "배포 완료"
          EOF